blank_issues_enabled: false
contact_links:
  - name: ✨ I want new features!
    url: https://www.oveleon.de/contao-entwicklung.html#angebot-anfordern
    about: Missing something in the contao cookiebar? Contract us to implement new features
  - name: 📖 View documentation
    url: https://github.com/oveleon/contao-cookiebar/tree/2.x/docs
    about: Read the cookiebar documentation
  - name: 💬 Question / Discussion
    url: https://community.contao.org/de/forumdisplay.php?180-Contao-Cookiebar-(Oveleon)
    about: Browse through frequently asked questions in the community forums or open a new topic
