cookiebar_blocker:
  path: /cookiebar/block/{id}
  defaults:
    _controller: "ContaoCookiebar:Cookiebar:block"
    _scope: frontend
  methods: [GET]

cookiebar_prepare:
  path: /cookiebar/{module}/{id}
  defaults:
    _controller: "ContaoCookiebar:Cookiebar:prepare"
    _scope: frontend
    _token_check: false
    id: null
  methods: [GET]
