services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Oveleon\ContaoCookiebar\:
        resource: '../../'
        exclude: '../../{Model,DependencyInjection,Resources,AbstractCookie.php,ContaoCookiebar.php,Cookiebar.php,CookieConfig.php,CookieHandler.php}'
